# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38994d61eb861d651de3f99c60905773c9c03bec0f863fbabaeeb178dad973cd832b3727874da9c92e8d32581143851769f28f1080c5fdc4d37d2ff56a67b45a

test:
  secret_key_base: ec9e7b36991efd12643aeee82e67b3f78d8df8cd92313c5393794ac29b93b5c0ed3dd924f4109700c1887c714a3a81193e82f882a61ed5e4264f82b48df47e5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
